# Magic Trees Productions Funding
# https://github.com/magictreesproductions

github: [magictreesproductions]
patreon: magictreesproductions
ko_fi: magictreesproductions
custom:
  - "https://buymeacoffee.com/magictreesproductions"
  - "https://magictreesproductions.com/support"
